# Generated by Django 4.1.3 on 2022-11-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('tipo_de_emprego', models.CharField(max_length=60)),
                ('nome_da_empresa', models.CharField(max_length=60)),
                ('localidade', models.CharField(max_length=60)),
                ('trabalho_atualmente_neste_cargo', models.BooleanField()),
                ('mes_inicio', models.CharField(max_length=50)),
                ('ano_inicio', models.CharField(max_length=50)),
                ('mes_fim', models.CharField(max_length=50)),
                ('ano_fim', models.CharField(max_length=50)),
                ('finalizar_cargo', models.BooleanField()),
                ('setor', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=2000)),
                ('titulo_do_perfil', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
