# Generated by Django 4.1.3 on 2022-11-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='exibir_que_linkedin_ajudou',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
