# Generated by Django 4.1.3 on 2022-11-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formacao',
        ),
    ]
