# Generated by Django 4.1.3 on 2022-11-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0001_initial'),
        ('user', '0002_delete_formacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='formacao_academica',
        ),
        migrations.AddField(
            model_name='user',
            name='formacao',
            field=models.ManyToManyField(to='formacao.formacao'),
        ),
    ]
