# Generated by Django 4.1.3 on 2022-11-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao_ensino', models.CharField(max_length=70)),
                ('diploma', models.CharField(max_length=70)),
                ('area_estudo', models.CharField(max_length=70)),
                ('mes_inicio', models.CharField(max_length=70)),
                ('ano_inicio', models.CharField(max_length=70)),
                ('mes_fim', models.CharField(max_length=70)),
                ('ano_fim', models.CharField(max_length=70)),
                ('nota', models.CharField(max_length=70)),
                ('atividades', models.TextField(max_length=500)),
                ('descricao', models.TextField(max_length=1000)),
            ],
        ),
    ]
